### ISSUE TITLE
EST does not handle duplicate secretKey usage in secrets

### ISSUE THREAD

**Issue by JonasKop** [JonasKop/external-secrets-transformer#15]
The following secret references the same keyvault secret in multiple places. When it is transformed it is converted into a ExternalSecret with duplicate secretKey items which is an invalid ExternalSecret object. Only unique SecretKeys should be added to the secretKey list.

**Input:**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example
stringData:
  MY_KEY: "{{ .someKey }}"
  MY_OTHER_KEY: "{{ .someKey }}"
```

**Output:**
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: example
    kind: example
  target:
    template:
      data:
        MY_KEY: '{{ .someKey }}'
        MY_OTHER_KEY: '{{ .someKey }}'
  data:
    - secretKey: someKey
      remoteRef:
        key: someKey
    - secretKey: someKey
      remoteRef:
        key: someKey
---
